#!/bin/sh

# ####################################################################
# go2fed - set of tools to automize packaging of golang devel codes
# Copyright (C) 2014  Jan Chaloupka, jchaloup@redhat.com
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
# ####################################################################

HELP=0
SCRATCH=1
BUILD=2
PARALLEL=3
UPDATE=4
GGI=5
GITHUB2SPEC=6
REVIEW=7
GOOGLECODE2SPEC=8
PULL=9
INSPECT=10
SCAN=11
SCANINFO=12
LINT=13
BUMP=14
CHECK_COMMIT=15
CHECK_DEPS=16
SCAN_IMPORTS=17
SCAN_PACKAGES=18
BBO=19
INITPKG=20
SCANDEPS=21
SCANSYMBOLS=22
GCPMASTER=23

operation=-1
script_dir=$(dirname $(readlink -f $0))

################################
################################
function printHelp {
	echo "Synopsis: go2fed command [arg1 [arg2 ...]]"
	echo ""
	echo "command:"
	echo "	help		 prints this help"
	echo "	scratch-build	 scratch build all fedora branches"
	echo "	build 		 build all fedora branches"
	echo "	update		 update all fedora branches"
	echo "	ggi		 get golang imports"
	echo "	github2spec	 generate spec file from github"
	echo "	googlecode2spec  generate spec file from googlecode"
	echo "	review		 creates review in Bugzilla (rpmbuild of spec file, rpmlint, koji build, ...)"
	echo "	pull		 pull from branches"
	echo "	inspect		 inspect golang tarball"
	echo "	scaninfo	 sumarize info from packages scan"
	echo "	scan		 scan golang packages listed in golang.packages"
	echo "	lint		 golang spec file checker"
	echo "	check-commit	 check package for commit"
	echo "	check-deps	 check packages for commit"
	echo "	scan-imports	 scan devel builds for possible import paths and imported paths"
	echo "	scan-packages	 scan PkgDB for possible golang packages"
	echo "	bbo		 buildroot override builds for all branches"
	echo "	initpkg		 get first build into Fedora from review request"
	echo "	scandeps	 scan all golang packages for dependencies (e.g. cyclic)"
	echo "	scansymbols	 scan directory for go symbols"
	echo "	gcpmaster	 git cherry pick master branch"

}

################################
################################
# $1 - command
if [ "$1" == "help" ]; then
	operation=$HELP
elif [ "$1" == "scratch-build" ]; then
	operation=$SCRATCH
elif [ "$1" == "build" ]; then
	operation=$BUILD
elif [ "$1" == "parallel-push" ]; then
	operation=$PARALLEL
elif [ "$1" == "update" ]; then
	operation=$UPDATE
elif [ "$1" == "ggi" ]; then
        operation=$GGI
elif [ "$1" == "github2spec" ]; then
        operation=$GITHUB2SPEC
elif [ "$1" == "googlecode2spec" ]; then
        operation=$GOOGLECODE2SPEC
elif [ "$1" == "review" ]; then
        operation=$REVIEW
elif [ "$1" == "pull" ]; then
        operation=$PULL
elif [ "$1" == "inspect" ]; then
        operation=$INSPECT
elif [ "$1" == "scaninfo" ]; then
        operation=$SCANINFO
elif [ "$1" == "scan" ]; then
        operation=$SCAN
elif [ "$1" == "lint" ]; then
        operation=$LINT
elif [ "$1" == "bump" ]; then
        operation=$BUMP
elif [ "$1" == "check-commit" ]; then
        operation=$CHECK_COMMIT
elif [ "$1" == "check-deps" ]; then
        operation=$CHECK_DEPS
elif [ "$1" == "scan-imports" ]; then
        operation=$SCAN_IMPORTS
elif [ "$1" == "scan-packages" ]; then
        operation=$SCAN_PACKAGES
elif [ "$1" == "bbo" ]; then
	operation=$BBO
elif [ "$1" == "initpkg" ]; then
        operation=$INITPKG
elif [ "$1" == "scandeps" ]; then
        operation=$SCANDEPS
elif [ "$1" == "scansymbols" ]; then
        operation=$SCANSYMBOLS
elif [ "$1" == "gcpmaster" ]; then
        operation=$GCPMASTER
fi

################################
################################
if [ $operation -eq -1 ]; then
	echo "Wrong operation"
	printHelp
	exit 0
fi

# dispose the $1 argument, operation already parsed
shift

if [ $operation -eq $HELP ]; then
	printHelp
elif [ $operation -eq $SCRATCH ]; then
	$script_dir/scratchbuildbranches.sh
elif [ $operation -eq $BUILD ]; then
	$script_dir/scratchbuildbranches.sh raw
elif [ $operation -eq $PARALLEL ]; then
	$script_dir/push2allbranches.sh
elif [ $operation -eq $UPDATE ]; then
	$script_dir/updateallbuilds.sh
elif [ $operation -eq $GGI ]; then
	$script_dir/ggi.py $@
elif [ $operation -eq $GITHUB2SPEC ]; then
        $script_dir/github2gospec.sh $@
elif [ $operation -eq $GOOGLECODE2SPEC ]; then
        $script_dir/googlecode2gospec.sh $@
elif [ $operation -eq $REVIEW ]; then
        $script_dir/preparePackageReview.sh $@
elif [ $operation -eq $PULL ]; then
        $script_dir/pullallbranches.sh
elif [ $operation -eq $INSPECT ]; then
        $script_dir/inspecttarball.py $@
elif [ $operation -eq $SCANINFO ]; then
        $script_dir/xml2info.py $@
elif [ $operation -eq $SCAN ]; then
        $script_dir/inspectPackages.sh $@
elif [ $operation -eq $LINT ]; then
        $script_dir/modules/specParser.py $@
elif [ $operation -eq $BUMP ]; then
        $script_dir/bumpSpec.py $@
elif [ $operation -eq $CHECK_COMMIT ]; then
        $script_dir/checkCommit.py $@
elif [ $operation -eq $CHECK_DEPS ]; then
        $script_dir/checkDeps.py $@
elif [ $operation -eq $SCAN_IMPORTS ]; then
        $script_dir/fetchImportPaths.py $@
elif [ $operation -eq $SCAN_PACKAGES ]; then
        $script_dir/getGolangPackages.py $@
elif [ $operation -eq $BBO ]; then
	$script_dir/bbobranches.py $@
elif [ $operation -eq $INITPKG ]; then
        $script_dir/initPackageInRepo.sh $@
elif [ $operation -eq $SCANDEPS ]; then
        $script_dir/discoverPkgDeps.py $@
elif [ $operation -eq $SCANSYMBOLS ]; then
        $script_dir/scanGoSymbols.py $@
elif [ $operation -eq $GCPMASTER ]; then
        $script_dir/gcpmaster.sh $@
fi

