#!/bin/sh

HELP=0
SCRATCH=1
BUILD=2
PARALLEL=3
UPDATE=4
GGI=5
GITHUB2SPEC=6
REVIEW=7
GOOGLECODE2SPEC=8
PULL=9
INSPECT=10
SCANINFO=11

operation=-1
script_dir=$(dirname $0)

################################
################################
function printHelp {
	echo "Synopsis: go2fed command [arg1 [arg2 ...]]"
	echo ""
	echo "command:"
	echo "	help		 prints this help"
	echo "	scratch-build	 scratch build all fedora branches"
	echo "	build 		 build all fedora branches"
	echo "	update		 update all fedora branches"
	echo "	ggi		 get golang imports"
	echo "	github2spec	 generate spec file from github"
	echo "	googlecode2spec  generate spec file from googlecode"
	echo "	review		 creates review in Bugzilla (rpmbuild of spec file, rpmlint, koji build, ...)"
	echo "	pull		 pull from branches"
	echo "	inspect		 inspect golang tarball"
	echo "	scaninfo	 sumarize info from packages scan"
}


################################
################################
# $1 - command
if [ "$1" == "help" ]; then
	operation=$HELP
elif [ "$1" == "scratch-build" ]; then
	operation=$SCRATCH
elif [ "$1" == "build" ]; then
	operation=$BUILD
elif [ "$1" == "parallel-push" ]; then
	operation=$PARALLEL
elif [ "$1" == "update" ]; then
	operation=$UPDATE
elif [ "$1" == "ggi" ]; then
        operation=$GGI
elif [ "$1" == "github2spec" ]; then
        operation=$GITHUB2SPEC
elif [ "$1" == "googlecode2spec" ]; then
        operation=$GOOGLECODE2SPEC
elif [ "$1" == "review" ]; then
        operation=$REVIEW
elif [ "$1" == "pull" ]; then
        operation=$PULL
elif [ "$1" == "inspect" ]; then
        operation=$INSPECT
elif [ "$1" == "scaninfo" ]; then
        operation=$SCANINFO
fi

################################
################################
if [ $operation -eq -1 ]; then
	echo "Wrong operation"
	printHelp
	exit 0
fi

# dispose the $1 argument, operation already parsed
shift

if [ $operation -eq $HELP ]; then
	printHelp
elif [ $operation -eq $SCRATCH ]; then
	$script_dir/scratchbuildbranches.sh
elif [ $operation -eq $BUILD ]; then
	$script_dir/scratchbuildbranches.sh raw
elif [ $operation -eq $PARALLEL ]; then
	$script_dir/push2allbranches.sh
elif [ $operation -eq $UPDATE ]; then
	$script_dir/updateallbuilds.sh
elif [ $operation -eq $GGI ]; then
	$script_dir/ggi.py $@
elif [ $operation -eq $GITHUB2SPEC ]; then
        $script_dir/github2gospec.sh $@
elif [ $operation -eq $GOOGLECODE2SPEC ]; then
        $script_dir/googlecode2gospec.sh $@
elif [ $operation -eq $REVIEW ]; then
        $script_dir/preparePackageReview.sh $@
elif [ $operation -eq $PULL ]; then
        $script_dir/pullallbranches.sh
elif [ $operation -eq $INSPECT ]; then
        $script_dir/inspecttarball.py $@
elif [ $operation -eq $SCANINFO ]; then
        $script_dir/xml2info.py $@
fi
